backend:
  name: git-gateway
  branch: main
collections:
  - name: "item"
    label: "Item"
    folder: "src/items"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: show
      value: true
    fields:
      - { label: "Item", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "item" }
      - {
          label: "Visibility",
          name: "visibility",
          widget: "boolean",
          default: true,
        }

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
