backend:
  name: git-gateway
  branch: main
collections:
  - name: "item"
    label: "Item"
    folder: "src/items"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: "Item", name: "title", widget: "string", default: "item" }
